require_relative 'ethermine/client'
require_relative 'ethermine/api/base_api'
require_relative 'ethermine/models/model'
require_relative 'ethermine/api/worker_api'
require_relative 'ethermine/models/worker/statistic'
